language: "perl"
perl:
  - "5.18"

before_install:
#    - sudo apt-get libxml2-dev zlib1g-dev
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc-4.8 g++-4.8
#    - CC=g++-4.8 cpanm -v Ufal::MorphoDiTa

env:
    - PERL5LIB=lib/
install:
    - cpanm --installdeps --notest Treex::Core
    - cpanm --notest URI::Find::Schemeless PerlIO::gzip Text::Iconv AI::MaxEntropy Cache::Memcached Email::Find XML::Twig String::Util String::Diff List::Pairwise MooseX::Role::AttributeOverride YAML::Tiny Graph Tree::Trie Text::Brew App::whichpm
    - cpanm Lingua::Interset
    #- CC=clang cpanm Ufal::MorphoDiTa Ufal::NameTag
    - CC=g++-4.8 cpanm -v Ufal::NameTag

script:
    - prove -r lib/Treex/Core
    #- lib/Treex/Tool/Tagger/t/morphodita.t
    - lib/Treex/Tool/NER/t/nametag_en.t
